### ISSUE TITLE
Provide minimized version of CSS resources

### ISSUE THREAD

**Issue by php-coder** [webjars/selectize.js#3]
If it's possible I want to have minimized version of CSS resources (like `selectize.bootstrap3.css`).

**Comment by jamesward** [comment]
This WebJar contains the upstream zip distribution: http://www.webjars.org/listfiles/selectize.js/0.12.1

If the upstream doesn't provide it, then either will the WebJar.

**Comment by php-coder** [comment]
selectize.js has been released a day ago. New version (0.13.2) should contain a fix. Could you, please, update it (or should I fill another issue for that)? Thanks!

**Comment by jamesward** [comment]
Cool. `0.13.2` will be released shortly. In the future, file a new issue.  Thanks!
